version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - if [ $STAGE = prod ]; then aws cloudfront help; echo "help"; fi;
      - npm test
artifacts:
  files:
    - '**/*'
