version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - aws cloudfront help
      - npm test
artifacts:
  files:
    - '**/*'
